title: Giovanni Sbattella
description: My website
url: "https://giovannisbattella.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.27.3

plugins:
  - jekyll-include-cache

author:
  name   : "Giovanni Sbattella"
  avatar : "/images/giovanni.jpg"
  bio    : "Complex macroeconomics"
  location: "Barcelona, ES"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giovannisbattella"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:giovanni.sbattella@bse.eu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giovanni-sbattella-877b22245/"
      
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:giovanni.sbattella@bse.eu"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giovannisbattella/"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giovanni-sbattella-877b22245/"
  since: "2024"
  
# Tell Jekyll to process _pages
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: single

# Navigation
header_pages:
  - /_pages/articles.md
  - /_pages/about.md
