title: Giovanni Sbattella
description: My website
remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-include-cache

  author:
  name   : "Giovanni Sbattella"
  avatar : "/assets/images/giovanni.jpg"
  bio    : "Complex macroeconomics"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/giovannisbattella"

# Enable posts
collections:
  posts:
    output: true

# Navigation
header_pages:
  - articles.md
  - about.md
